// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5mb0IdjXtVjSQ1uYLTjGaOeTLbU5qD8Y',
    appId: '1:528868523236:web:80d9a239da6fa9d6d980f1',
    messagingSenderId: '528868523236',
    projectId: 'todo-app-c11-cbca2',
    authDomain: 'todo-app-c11-cbca2.firebaseapp.com',
    storageBucket: 'todo-app-c11-cbca2.firebasestorage.app',
    measurementId: 'G-TCBTP4V1PM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3UN7Vwdj4TAsGR-XQJ5n0MFRqBIkUWCw',
    appId: '1:528868523236:android:38c77b47ff0beff5d980f1',
    messagingSenderId: '528868523236',
    projectId: 'todo-app-c11-cbca2',
    storageBucket: 'todo-app-c11-cbca2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClEIcadefqyo5wyWBbGn6WQdvcuTxPksY',
    appId: '1:528868523236:ios:48408cc6ff0d2530d980f1',
    messagingSenderId: '528868523236',
    projectId: 'todo-app-c11-cbca2',
    storageBucket: 'todo-app-c11-cbca2.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClEIcadefqyo5wyWBbGn6WQdvcuTxPksY',
    appId: '1:528868523236:ios:48408cc6ff0d2530d980f1',
    messagingSenderId: '528868523236',
    projectId: 'todo-app-c11-cbca2',
    storageBucket: 'todo-app-c11-cbca2.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5mb0IdjXtVjSQ1uYLTjGaOeTLbU5qD8Y',
    appId: '1:528868523236:web:30619fa8bb0b26dad980f1',
    messagingSenderId: '528868523236',
    projectId: 'todo-app-c11-cbca2',
    authDomain: 'todo-app-c11-cbca2.firebaseapp.com',
    storageBucket: 'todo-app-c11-cbca2.firebasestorage.app',
    measurementId: 'G-2416KY3ZG0',
  );
}
